/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe: process is up and serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe: report connectivity to each backing service.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_v1_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{code_commune}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get City */
        get: operations["get_city_api_v1_cities__code_commune__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/housing/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prices */
        get: operations["list_prices_api_v1_housing_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arrondissements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Arrondissements */
        get: operations["list_arrondissements_api_v1_arrondissements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arrondissements/{code_arrondissement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arrondissement */
        get: operations["get_arrondissement_api_v1_arrondissements__code_arrondissement__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobility/gares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gares */
        get: operations["list_gares_api_v1_mobility_gares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get National */
        get: operations["get_national_api_v1_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/national/housing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get National Housing */
        get: operations["get_national_housing_api_v1_national_housing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArrondissementDetail */
        ArrondissementDetail: {
            /** Code Arrondissement */
            code_arrondissement: string;
            /** Year */
            year?: number | null;
            /** Nom Arrondissement */
            nom_arrondissement: string;
            /** Code Commune Parent */
            code_commune_parent: string;
            /** Nom Commune Parent */
            nom_commune_parent?: string | null;
            /** Code Departement */
            code_departement: string;
            /** Region */
            region?: string | null;
            /** Population */
            population?: number | null;
            /** Insee Ref Year */
            insee_ref_year?: number | null;
            /** Revenu Median */
            revenu_median?: number | null;
            /** Revenu Ref Year */
            revenu_ref_year?: number | null;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Type Commune */
            type_commune?: string | null;
            /** Affordability Years */
            affordability_years?: number | null;
            /** M2 Par An */
            m2_par_an?: number | null;
            /** Affordability Class */
            affordability_class?: string | null;
            /**
             * Metrics By Year
             * @default []
             */
            metrics_by_year: components["schemas"]["ArrondissementYearlyMetric"][];
        };
        /** ArrondissementMetrics */
        ArrondissementMetrics: {
            /** Code Arrondissement */
            code_arrondissement: string;
            /** Year */
            year?: number | null;
            /** Nom Arrondissement */
            nom_arrondissement: string;
            /** Code Commune Parent */
            code_commune_parent: string;
            /** Nom Commune Parent */
            nom_commune_parent?: string | null;
            /** Code Departement */
            code_departement: string;
            /** Region */
            region?: string | null;
            /** Population */
            population?: number | null;
            /** Insee Ref Year */
            insee_ref_year?: number | null;
            /** Revenu Median */
            revenu_median?: number | null;
            /** Revenu Ref Year */
            revenu_ref_year?: number | null;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Type Commune */
            type_commune?: string | null;
            /** Affordability Years */
            affordability_years?: number | null;
            /** M2 Par An */
            m2_par_an?: number | null;
            /** Affordability Class */
            affordability_class?: string | null;
        };
        /**
         * ArrondissementYearlyMetric
         * @description One DVF vintage of headline metrics for an arrondissement.
         */
        ArrondissementYearlyMetric: {
            /** Year */
            year: number;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
            /** Affordability Years */
            affordability_years?: number | null;
            /** Affordability Class */
            affordability_class?: string | null;
        };
        /** CityDetail */
        CityDetail: {
            /** Code Commune */
            code_commune: string;
            /** Year */
            year?: number | null;
            /** Nom Commune */
            nom_commune: string;
            /** Code Departement */
            code_departement: string;
            /** Region */
            region?: string | null;
            /** Population */
            population?: number | null;
            /** Insee Ref Year */
            insee_ref_year?: number | null;
            /** Revenu Median */
            revenu_median?: number | null;
            /** Revenu Ref Year */
            revenu_ref_year?: number | null;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Type Commune */
            type_commune?: string | null;
            /** Affordability Years */
            affordability_years?: number | null;
            /** M2 Par An */
            m2_par_an?: number | null;
            /** Affordability Class */
            affordability_class?: string | null;
            /** Nb Gares */
            nb_gares?: number | null;
            /** Distance Gare Km */
            distance_gare_km?: number | null;
            /** Gare Proche Nom */
            gare_proche_nom?: string | null;
            /** Desserte Class */
            desserte_class?: string | null;
            /** Niveau Equipement */
            niveau_equipement?: string | null;
            /** Nb Total Equipements */
            nb_total_equipements?: number | null;
            /** Nb Sante */
            nb_sante?: number | null;
            /** Nb Commerces */
            nb_commerces?: number | null;
            /** Nb Enseignement */
            nb_enseignement?: number | null;
            /** Nb Supermarche */
            nb_supermarche?: number | null;
            /** Pct Moins25 */
            pct_moins25?: number | null;
            /** Pct 25 64 */
            pct_25_64?: number | null;
            /** Pct 65Plus */
            pct_65plus?: number | null;
            /**
             * Metrics By Year
             * @default []
             */
            metrics_by_year: components["schemas"]["YearlyMetric"][];
            /**
             * Trend
             * @default []
             */
            trend: components["schemas"]["PriceTrendPoint"][];
        };
        /** CityMetrics */
        CityMetrics: {
            /** Code Commune */
            code_commune: string;
            /** Year */
            year?: number | null;
            /** Nom Commune */
            nom_commune: string;
            /** Code Departement */
            code_departement: string;
            /** Region */
            region?: string | null;
            /** Population */
            population?: number | null;
            /** Insee Ref Year */
            insee_ref_year?: number | null;
            /** Revenu Median */
            revenu_median?: number | null;
            /** Revenu Ref Year */
            revenu_ref_year?: number | null;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Type Commune */
            type_commune?: string | null;
            /** Affordability Years */
            affordability_years?: number | null;
            /** M2 Par An */
            m2_par_an?: number | null;
            /** Affordability Class */
            affordability_class?: string | null;
            /** Nb Gares */
            nb_gares?: number | null;
            /** Distance Gare Km */
            distance_gare_km?: number | null;
            /** Gare Proche Nom */
            gare_proche_nom?: string | null;
            /** Desserte Class */
            desserte_class?: string | null;
            /** Niveau Equipement */
            niveau_equipement?: string | null;
            /** Nb Total Equipements */
            nb_total_equipements?: number | null;
            /** Nb Sante */
            nb_sante?: number | null;
            /** Nb Commerces */
            nb_commerces?: number | null;
            /** Nb Enseignement */
            nb_enseignement?: number | null;
            /** Nb Supermarche */
            nb_supermarche?: number | null;
            /** Pct Moins25 */
            pct_moins25?: number | null;
            /** Pct 25 64 */
            pct_25_64?: number | null;
            /** Pct 65Plus */
            pct_65plus?: number | null;
        };
        /** Gare */
        Gare: {
            /** Code Uic */
            code_uic: string;
            /** Nom Gare */
            nom_gare: string;
            /** Code Commune */
            code_commune?: string | null;
            /** Segment Drg */
            segment_drg?: string | null;
            /** Frequentation */
            frequentation?: number | null;
            /** Frequentation Year */
            frequentation_year?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HousingPriceByType */
        HousingPriceByType: {
            /** Code Commune */
            code_commune: string;
            /** Type Local */
            type_local: string;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
        };
        /** Page[ArrondissementMetrics] */
        Page_ArrondissementMetrics_: {
            /** Items */
            items: components["schemas"]["ArrondissementMetrics"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[CityMetrics] */
        Page_CityMetrics_: {
            /** Items */
            items: components["schemas"]["CityMetrics"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[Gare] */
        Page_Gare_: {
            /** Items */
            items: components["schemas"]["Gare"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[HousingPriceByType] */
        Page_HousingPriceByType_: {
            /** Items */
            items: components["schemas"]["HousingPriceByType"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PriceTrendPoint */
        PriceTrendPoint: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * YearlyMetric
         * @description One DVF vintage of headline metrics for a commune.
         */
        YearlyMetric: {
            /** Year */
            year: number;
            /** Prix M2 Median */
            prix_m2_median?: number | null;
            /** Prix M2 Mean */
            prix_m2_mean?: number | null;
            /** Surface Median */
            surface_median?: number | null;
            /**
             * Nb Transactions
             * @default 0
             */
            nb_transactions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_cities_api_v1_cities_get: {
        parameters: {
            query?: {
                /** @description Filter by 2-3 char dept code */
                departement?: string | null;
                /** @description Case-insensitive name search */
                q?: string | null;
                /** @description Sort column */
                sort?: string;
                order?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CityMetrics_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_city_api_v1_cities__code_commune__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_commune: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prices_api_v1_housing_prices_get: {
        parameters: {
            query?: {
                code_commune?: string | null;
                /** @description Maison | Appartement */
                type_local?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HousingPriceByType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_arrondissements_api_v1_arrondissements_get: {
        parameters: {
            query?: {
                /** @description Filter by dept (75 | 69 | 13) */
                departement?: string | null;
                /** @description Filter by parent commune INSEE code (e.g. 75056) */
                code_commune_parent?: string | null;
                /** @description Sort column */
                sort?: string;
                order?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ArrondissementMetrics_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_arrondissement_api_v1_arrondissements__code_arrondissement__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_arrondissement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrondissementDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gares_api_v1_mobility_gares_get: {
        parameters: {
            query?: {
                /** @description Filter by 2-char dept code */
                departement?: string | null;
                /** @description Filter by commune INSEE code */
                code_commune?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Gare_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_national_api_v1_national_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityDetail"];
                };
            };
        };
    };
    get_national_housing_api_v1_national_housing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HousingPriceByType_"];
                };
            };
        };
    };
}
